name: "CI"
on:
  pull_request:
    branches: [main]
  push:
    branches: [develop]
jobs:
  test-github-actions:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: mongodb://mongo:27017/test_git
      NODE_ENV: test

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 22
          cache: npm
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.1
        with:
          mongodb-version: 7

      - name: Wait for MongoDB
        run: |
          npm install mongodb --save-dev
          node -e "require('mongodb').MongoClient.connect('mongodb://localhost:27017/test_git', (err, client) => { if (err) process.exit(1); client.close(); })"
        timeout-minutes: 2

      - name: install dependecies
        run: npm ci

      - name: lint application
        run: npm run lint

      - name: format code
        run: npm run format

      - name: run tests
        run: npm test
        timeout-minutes: 10
